export const data = [
  {
    picture: '/img/avatars/helen.jpg',
    name: "Brielle Kuphal",
    email: "Brielle31@gmail.com",
    job: "Business analyst",
    country: "Tunisia",
    year: 1989,
  },
  {
    picture: '/img/avatars/aaron.jpg',
    name: "Barney Murray",
    email: "Barney75@gmail.com",
    job: "Solution architect",
    country: "Haiti",
    year: 1970,
  },
  {
    picture: '/img/avatars/carolin.jpg',
    name: "Ressie Ruecker",
    email: "Ressie.Ruecker30@gmail.com",
    job: "UX designer",
    country: "Germany",
    year: 1967,
  },
  {
    picture: '/img/avatars/betty.jpg',
    name: "Teresa Mertz",
    email: "Teresa_Mertz@hotmail.com",
    job: "Sales Manager",
    country: "Bahrain",
    year: 1953,
  },
  {
    picture: null,
    name: "Chelsey Hackett",
    email: "Chelsey_Hackett@gmail.com",
    job: "Accountant",
    country: "Malta",
    year: 1962,
  },
  {
    picture: '/img/avatars/jane.jpg',
    name: "Tatyana Metz",
    email: "Tatyana_Metz91@gmail.com",
    job: "Product manager",
    country: "Sierra Leone",
    year: 1983,
  },
  {
    picture: '/img/avatars/marge.jpg',
    name: "Oleta Harvey",
    email: "Oleta_Harvey@yahoo.com",
    job: "Frontend developer",
    country: "Brazil",
    year: 1963,
  },
  {
    picture: '/img/avatars/mila.jpg',
    name: "Bette Haag",
    email: "Bette.Haag99@gmail.com",
    job: "Backend developer",
    country: "Guyana",
    year: 1974,
  },
  {
    picture: null,
    name: "Meda Ebert",
    email: "Meda_Ebert8@yahoo.com",
    job: "Sales manager",
    country: "Spain",
    year: 1964,
  },
  {
    picture: '/img/avatars/mira.jpg',
    name: "Elissa Stroman",
    email: "Elissa.Stroman6@yahoo.com",
    job: "HR Manager",
    country: "USA",
    year: 1978,
  },
  {
    picture: null,
    name: "Sid Swaniawski",
    email: "Sid_Swaniawski@hotmail.com",
    job: "UI designer",
    country: "Gibraltar",
    year: 1979,
  },
  {
    picture: null,
    name: "Madonna Hahn",
    email: "Madonna10@gmail.com",
    job: "Customer support",
    country: "Ireland",
    year: 1968,
  },
  {
    picture: '/img/avatars/marc.jpg',
    name: "Waylon Kihn",
    email: "Waylon27@yahoo.com",
    job: "Support agent",
    country: "China",
    year: 1958,
  },
  {
    picture: null,
    name: "Jaunita Lindgren",
    email: "Jaunita_Lindgren@yahoo.com",
    job: "Solution architect",
    country: "Sweden",
    year: 1958,
  },
  {
    picture: '/img/avatars/stacy.jpg',
    name: "Lenora MacGyver",
    email: "Lenora_MacGyver@yahoo.com",
    job: "Marketing associate",
    country: "Estonia",
    year: 1981,
  },
  {
    picture: '/img/avatars/nick.jpg',
    name: "Ole Collier",
    email: "Ole51@hotmail.com",
    job: "Web developer",
    country: "Cape Verde",
    year: 1977,
  },
  {
    picture: null,
    name: "Taurean Koelpin",
    email: "Taurean.Koelpin@gmail.com",
    job: "Frontend developer",
    country: "Cameroun",
    year: 1980,
  },
  {
    picture: '/img/avatars/melany.jpg',
    name: "Thalia Yost",
    email: "Thalia73@gmail.com",
    job: "CEO",
    country: "Poland",
    year: 1988,
  },
  {
    picture: '/img/avatars/sayid.jpg',
    name: "Okey Kling",
    email: "Okey84@gmail.com",
    job: "HR manager",
    country: "Poland",
    year: 1973,
  },
  {
    picture: null,
    name: "Darrick Ortiz",
    email: "Darrick73@yahoo.com",
    job: "QA Agent",
    country: "India",
    year: 1990,
  },
  {
    picture: null,
    name: "Eulalia Vandervort",
    email: "Eulalia.Vandervort63@gmail.com",
    job: "Freelancer",
    country: "Spain",
    year: 1990,
  },
  {
    picture: '/img/avatars/lakisha.jpg',
    name: "Genevieve Pouros",
    email: "Genevieve29@hotmail.com",
    job: "Business analyst",
    country: "France",
    year: 1983,
  },
  {
    picture: null,
    name: "Horacio Purdy",
    email: "Horacio65@yahoo.com",
    job: "CFO",
    country: "Slovakia",
    year: 1968,
  },
  {
    picture: '/img/avatars/john.jpg',
    name: "Eleazar Konopelski",
    email: "Eleazar_Konopelski@hotmail.com",
    job: "Engineer",
    country: "Chili",
    year: 1954,
  },
  {
    picture: null,
    name: "Herminia Effertz",
    email: "Herminia.Effertz78@gmail.com",
    job: "Team Manager",
    country: "Germany",
    year: 1964,
  },
  {
    picture: '/img/avatars/kareem.jpg',
    name: "Brian Hermann",
    email: "Brian12@hotmail.com",
    job: "Product manager",
    country: "Germany",
    year: 1952,
  },
  {
    picture: null,
    name: "Wellington Barrows",
    email: "Wellington.Barrows@gmail.com",
    job: "Customer support",
    country: "Zimbabwe",
    year: 1977,
  },
  {
    picture: '/img/avatars/jhonny.jpg',
    name: "David Rosenbaum",
    email: "David75@hotmail.com",
    job: "System administrator",
    country: "Mayotte",
    year: 1988,
  },
  {
    picture: null,
    name: "Pinkie Reilly",
    email: "Pinkie.Reilly67@gmail.com",
    job: "Technical lead",
    country: "Australia",
    year: 1973,
  },
  {
    picture: '/img/avatars/janet.jpg',
    name: "Asha Bartell",
    email: "Asha82@gmail.com",
    job: "Marketing manager",
    country: "Tonga",
    year: 1991,
  },
  {
    picture: '/img/avatars/elisabeth.jpg',
    name: "Alexane Bode",
    email: "Alexane_Bode30@yahoo.com",
    job: "Wen developer",
    country: "Honduras",
    year: 1969,
  },
  {
    picture: null,
    name: "Estelle Bode",
    email: "Estelle_Bode@yahoo.com",
    job: "Lead Marketing",
    country: "Honduras",
    year: 1972,
  },
  {
    picture: null,
    name: "Jeromy Mayer",
    email: "Jeromy39@yahoo.com",
    job: "UX designer",
    country: "Maldives",
    year: 1973,
  },
  {
    picture: '/img/avatars/eric.jpg',
    name: "Ephraim Wiegand",
    email: "Ephraim88@gmail.com",
    job: "Direct Identity Administrator",
    country: "Australia",
    year: 1946,
  },
  {
    picture: '/img/avatars/fred.jpg',
    name: "Jarrett Grimes",
    email: "Jarrett.Grimes99@gmail.com",
    job: "Web Strategist",
    country: "United Kingdom",
    year: 1986,
  },
  {
    picture: null,
    name: "Jeffry Macejkovic",
    email: "Jeffry_Macejkovic40@hotmail.com",
    job: "Product manager",
    country: "USA",
    year: 1959,
  },
  {
    picture: '/img/avatars/eleanor.jpg',
    name: "Janelle Stroman",
    email: "Janelle_Stroman@yahoo.com",
    job: "HR manager",
    country: "Denmark",
    year: 1974,
  },
  {
    picture: null,
    name: "Camille Considine",
    email: "Camille79@gmail.com",
    job: "UX designer",
    country: "France",
    year: 1975,
  },
  {
    picture: null,
    name: "Amani Schinner",
    email: "Amani.Schinner@yahoo.com",
    job: "Corporate Metrics Manager",
    country: "Sri Lanka",
    year: 1981,
  },
  {
    picture: '/img/avatars/dan.jpg',
    name: "Dustin Bahringer",
    email: "Dustin76@hotmail.com",
    job: "Graphic Designer",
    country: "Ukraine",
    year: 1988,
  },
  {
    picture: '/img/avatars/elie.jpg',
    name: "Mary Sanford",
    email: "Mary44@yahoo.com",
    job: "Accountant",
    country: "USA",
    year: 1979,
  },
  {
    picture: null,
    name: "Itzel Skiles",
    email: "Itzel32@gmail.com",
    job: "Fullstack developer",
    country: "Israel",
    year: 1981,
  },
  {
    picture: null,
    name: "Melyssa Denesik",
    email: "Melyssa_Denesik@hotmail.com",
    job: "Mobile developer",
    country: "Lebanon",
    year: 1990,
  },
  {
    picture: '/img/avatars/betty.jpg',
    name: "Elenora McLaughlin",
    email: "Elenora_McLaughlin@yahoo.com",
    job: "Legacy Engineer",
    country: "USA",
    year: 1984,
  },
  {
    picture: null,
    name: "Chet Lueilwitz",
    email: "Chet_Lueilwitz98@yahoo.com",
    job: "Producer",
    country: "Togo",
    year: 1967,
  },
  {
    picture: '/img/avatars/ben.jpg',
    name: "Adrian Ondricka",
    email: "adrian.ondricka@hotmail.com",
    job: "UX Designer",
    country: "Germany",
    year: 1991,
  },
  {
    picture: '/img/avatars/arthur.jpg',
    name: "Bernardo Krajcik",
    email: "Bernardo_Krajcik81@hotmail.com",
    job: "Fullstack developer",
    country: "Serbia",
    year: 1979,
  },
  {
    picture: null,
    name: "Aiyana Kshlerin",
    email: "Aiyana64@hotmail.com",
    job: "Product manager",
    country: "Netherlands",
    year: 1971,
  },
  {
    picture: null,
    name: "Ambrose Anderson",
    email: "Ambrose32@yahoo.com",
    job: "Central Solutions Executive",
    country: "Moldova",
    year: 1986,
  },
  {
    picture: '/img/avatars/helen.jpg',
    name: "Margie Kreiger",
    email: "Margie_Kreiger@gmail.com",
    job: "Corporate Analyst",
    country: "USA",
    year: 1983,
  },
  {
    picture: '/img/avatars/carolin.png',
    name: "Adrianna Heller",
    email: "adrianna.heller23@yahoo.com",
    job: "Project manager",
    country: "England",
    year: 1962,
  },
  {
    picture: null,
    name: "Helena Wuckert",
    email: "Helena.Wuckert34@hotmail.com",
    job: "Metrics analyst",
    country: "Portugal",
    year: 1962,
  },
  {
    picture: null,
    name: "Boyd Bruen",
    email: "Boyd22@gmail.com",
    job: "Backend developer",
    country: "USA",
    year: 1987,
  },
  {
    picture: '/img/avatars/ben.jpg',
    name: "Spencer Zieme",
    email: "Spencer.Zieme@yahoo.com",
    job: "Web developer",
    country: "Germany",
    year: 1977,
  },
  {
    picture: '/img/avatars/william.jpg',
    name: "Kamron Muller",
    email: "Kamron3@yahoo.com",
    job: "Customer strategist",
    country: "Germany",
    year: 1969,
  },
  {
    picture: '/img/avatars/stella.jpg',
    name: "Betsy Wiegand",
    email: "Betsy.Wiegand@gmail.com",
    job: "Product manager",
    country: "Finland",
    year: 1985,
  },
  {
    picture: null,
    name: "Tressa Hettinger",
    email: "Tressa.Hettinger@hotmail.com",
    job: "Mobile developer",
    country: "Montenegro",
    year: 1986,
  },
  {
    picture: '/img/avatars/nicole.jpg',
    name: "Bella Kunze",
    email: "Bella.Kunze@hotmail.com",
    job: "District Branding Designer",
    country: "Romania",
    year: 1975,
  },
  {
    picture: '/img/avatars/ray.jpg',
    name: "Bradford Quitzon",
    email: "Bradford3@yahoo.com",
    job: "Project manager",
    country: "Vanuatu",
    year: 1992,
  },
  {
    picture: '/img/avatars/henry.jpg',
    name: "Adrien Gerhold",
    email: "Adrien73@yahoo.com",
    job: "Fullstack developer",
    country: "France",
    year: 1978,
  },
  {
    picture: '/img/avatars/russel.jpg',
    name: "Micheal Walter",
    email: "Micheal.Walter62@gmail.com",
    job: "Team Coordinator",
    country: "USA",
    year: 1990,
  },
  {
    picture: '/img/avatars/jalil.jpg',
    name: "Alberto Glover",
    email: "Alberto14@hotmail.com",
    job: "Software Engineer",
    country: "Argentina",
    year: 1962,
  },
  {
    picture: null,
    name: "Quinn Stark",
    email: "Quinn.Stark46@hotmail.com",
    job: "Markets Analyst",
    country: "Czech Republic",
    year: 1977,
  },
  {
    picture: '/img/avatars/alan.jpg',
    name: "Deven Stark",
    email: "Deven_Stark@hotmail.com",
    job: "Software engineer",
    country: "Serbia",
    year: 1991,
  },
  {
    picture: null,
    name: "Clare Hickle",
    email: "Clare59@gmail.com",
    job: "System administrator",
    country: "Kenya",
    year: 1985,
  },
  {
    picture: '/img/avatars/barry.jpg',
    name: "Kendall DAmore",
    email: "Kendall77@yahoo.com",
    job: "Corporate Consultant",
    country: "USA",
    year: 1982,
  },
  {
    picture: '/img/avatars/christina.jpg',
    name: "Keeley Gleichner",
    email: "Keeley_Gleichner@yahoo.com",
    job: "Operations officer",
    country: "Kenya",
    year: 1975,
  },
  {
    picture: null,
    name: "Nikita Fahey",
    email: "Nikita_Fahey@gmail.com",
    job: "Investment Analyst",
    country: "Vanuatu",
    year: 1972,
  },
  {
    picture: null,
    name: "Kassandra Kuvalis",
    email: "Kassandra1@yahoo.com",
    job: "Mobility manager",
    country: "Ireland",
    year: 1976,
  },
  {
    picture: '/img/avatars/dan.png',
    name: "Edwin Willms",
    email: "Edwin30@yahoo.com",
    job: "Creative director",
    country: "Finland",
    year: 1989,
  },
  {
    picture: null,
    name: "Jaylan Yundt",
    email: "Jaylan_Yundt@gmail.com",
    job: "UX Designer",
    country: "Sweden",
    year: 1972,
  },
  {
    picture: '/img/avatars/melany.jpg',
    name: "Claudie Heidenreich",
    email: "Claudie.Heidenreich20@yahoo.com",
    job: "Regional Director",
    country: "Germany",
    year: 1990,
  },
  {
    picture: '/img/avatars/mila.jpg',
    name: "Vernice Mann",
    email: "Vernice61@yahoo.com",
    job: "Software engineer",
    country: "France",
    year: 1979,
  },
  {
    picture: null,
    name: "Isabella Christiansen",
    email: "Isabella_Christiansen56@hotmail.com",
    job: "Solution architect",
    country: "Norway",
    year: 1973,
  },
  {
    picture: '/img/avatars/alex.jpg',
    name: "Ronny Dietrich",
    email: "Ronny.Dietrich@hotmail.com",
    job: "Investor Metrics",
    country: "Austrich",
    year: 1985,
  },
  {
    picture: null,
    name: "Trey Ritchie",
    email: "Trey.Ritchie0@gmail.com",
    job: "Mobility Officer",
    country: "USA",
    year: 1988,
  },
  {
    picture: null,
    name: "Jarvis Bauch",
    email: "Jarvis77@gmail.com",
    job: "HR manager",
    country: "USA",
    year: 1991,
  },
  {
    picture: '/img/avatars/nina.jpg',
    name: "Alanis Torp",
    email: "Alanis61@hotmail.com",
    job: "HR Manager",
    country: "USA",
    year: 1966,
  },
  {
    picture: null,
    name: "Katelynn Reichert",
    email: "Katelynn.Reichert38@gmail.com",
    job: "Brand Designer",
    country: "England",
    year: 1972,
  },
  {
    picture: null,
    name: "Ibrahim Stroman",
    email: "Ibrahim_Stroman@hotmail.com",
    job: "Marketing Planner",
    country: "Qatar",
    year: 1984,
  },
  {
    picture: '/img/avatars/sally.jpg',
    name: "Edyth McCullough",
    email: "Edyth_McCullough12@hotmail.com",
    job: "Human Integration Manager",
    country: "Belgium",
    year: 1992,
  },
];
